service: picker-data

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8

package:
  artifact: build/distributions/generate-picker-data-file.zip

functions:
  generate:
    handler: com.serverless.GenerateHandler
    events:
      - http:
          path: generate/{id}
          method: post
          request:
          parameters:
            paths:
              id: true
  fetch:
    handler: com.serverless.FetchHandler
    events:
      - http:
          path: fetch
          method: get
